encryption = "age"
color = "on"
mode = "symlink"
progress = true
[git]
    autoPush = true
[age]
    identity = "~/key.txt"
    recipient = "age1unnpzwvzjy497ycnpgjgkwxdty75cddshnnrl52yuypskjxgcyrq547zp5"
