#! /bin/sh

# Keybindings
pgrep -x sxhkd > /dev/null || sxhkd &


# Background
# feh --bg-scale $HOME/Pictures/desktop-background.jpg

# Setup Displays
xrandr --output eDP1 --mode 1366x768 --rate 60 --primary --current

# Picom Compositor
picom --config $HOME/.config/picom/picom.conf -bc


# Polybar
$HOME/.config/polybar/launch.sh


bspc config external_rules_command $HOME/.config/bspwm/bspwm-rules



bspc monitor eDP1  -d I II III IV V VI VII VIII IX X


bspc config border_width         1
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Start Applications
# discord &
# spotify &